version: v1.1.0

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:4200
        - http://localhost:8082
        - http://localhost:8080
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:4200
  allowed_return_urls:
    - http://localhost:4200

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      config:
        providers:
          - id: google
            provider: generic
            # Google client id and secret are set via env variables:
            # client_id = SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID
            # client_secret = SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET
            issuer_url: https://accounts.google.com
            mapper_url: file:///etc/config/kratos/google.jsonnet
            scope:
              - email
              - profile
              - openid
      enabled: true

  flows:
    error:
      ui_url: http://localhost:4200/auth/error

    settings:
      ui_url: http://localhost:4200/settings/profile
      privileged_session_max_age: 15m
      required_aal: highest_available

      # before:
      #   hooks:
      #    - hook: web_hook
      #      config:
      #        url: http://dockerhost:8082/ory-hooks/settings
      #        method: POST
      #        # base64 encoded jsonnet template ./settings_hook.jsonnet
      #        body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgdXNlcklkOiBjdHguaWRlbnRpdHkuaWQsCiAgdHJhaXRzOiB7CiAgICBlbWFpbDogY3R4LmlkZW50aXR5LnRyYWl0cy5lbWFpbCwKICAgIG5hbWU6IGN0eC5pZGVudGl0eS50cmFpdHMubmFtZSwKICB9LAp9
      #        response:
      #          ignore: false
      #          parse: false


    recovery:
      enabled: true
      ui_url: http://localhost:4200/auth/recovery
      use: code
      after:
        default_browser_return_url: http://localhost:4200

    verification:
      enabled: true
      ui_url: http://localhost:4200/auth/verification
      use: code
      after:
        default_browser_return_url: http://localhost:4200

    logout:
      after:
        default_browser_return_url: http://localhost:4200/auth/login

    login:
      ui_url: http://localhost:4200/auth/login
      lifespan: 10m
      after:
        default_browser_return_url: http://localhost:4200
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://host.docker.internal:8082/hooks/login
                method: POST
                # base64 encoded jsonnet template ./registration_hook.jsonnet
                body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgdXNlcklkOiBjdHguaWRlbnRpdHkuaWQsCiAgdHJhaXRzOiB7CiAgICBlbWFpbDogY3R4LmlkZW50aXR5LnRyYWl0cy5lbWFpbCwKICAgIG5hbWU6IGN0eC5pZGVudGl0eS50cmFpdHMubmFtZSwKICB9LAp9
                response:
                  ignore: false
                  parse: false
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://host.docker.internal:8082/hooks/login
                method: POST
                # base64 encoded jsonnet template ./registration_hook.jsonnet
                body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgdXNlcklkOiBjdHguaWRlbnRpdHkuaWQsCiAgdHJhaXRzOiB7CiAgICBlbWFpbDogY3R4LmlkZW50aXR5LnRyYWl0cy5lbWFpbCwKICAgIG5hbWU6IGN0eC5pZGVudGl0eS50cmFpdHMubmFtZSwKICB9LAp9
                response:
                  ignore: false
                  parse: false

    registration:
      lifespan: 10m
      ui_url: http://localhost:4200/auth/registration
      after:
        default_browser_return_url: http://localhost:4200
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
            - hook: web_hook
              config:
                url: http://host.docker.internal:8082/hooks/register
                method: POST
                # base64 encoded jsonnet template ./registration_hook.jsonnet
                body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgdXNlcklkOiBjdHguaWRlbnRpdHkuaWQsCiAgdHJhaXRzOiB7CiAgICBlbWFpbDogY3R4LmlkZW50aXR5LnRyYWl0cy5lbWFpbCwKICAgIG5hbWU6IGN0eC5pZGVudGl0eS50cmFpdHMubmFtZSwKICB9LAp9
                response:
                  ignore: false
                  parse: false
        oidc:
          hooks:
            - hook: session
            - hook: show_verification_ui
            - hook: web_hook
              config:
                url: http://host.docker.internal:8082/hooks/register
                method: POST
                # base64 encoded jsonnet template ./registration_hook.jsonnet
                body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgdXNlcklkOiBjdHguaWRlbnRpdHkuaWQsCiAgdHJhaXRzOiB7CiAgICBlbWFpbDogY3R4LmlkZW50aXR5LnRyYWl0cy5lbWFpbCwKICAgIG5hbWU6IGN0eC5pZGVudGl0eS50cmFpdHMubmFtZSwKICB9LAp9
                response:
                  ignore: false
                  parse: false

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json
