name: chatapp

volumes:
  postgres_data:

networks:
  intranet:

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASES=postgres
    ports:
      - 5432:5432
    volumes:
      - ./config/db/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/postgres?search_path=users&sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    networks:
      - intranet

  kratos:
    image: oryd/kratos
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/postgres?search_path=users&sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - '4433:4433'
      - '4434:4434'
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    networks:
      - intranet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # TODO: Change it to mailhog
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
    networks:
      - intranet
