version: "3.7"


volumes:
  postgres_data:


services:

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 120

  application-migrate:
    build: ./application_migrate
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      PGPASSWORD: password
      DB_NAME: chat
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
