# This is local config.
# It allow to run database, ejabberd, kratos and mailslurper in docker environment
# but main application should be runnig manualy to simplify development. All configs
# for this environment contiain "localhost" instead of docker hosts aliases and 
# connect with outerworld via "host.docker.internal:host-gateway".
# To run everything in docker configuration should be changed!

name: chatapp

volumes:
  postgres_data:

networks:
  intranet:

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpassword
      - POSTGRES_MULTIPLE_DATABASES=kratos,ejabberd
    ports:
      - 5432:5432
    volumes:
      - ./config/db/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatuser -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v1.2.0
    environment:
      # we do not need to create separate "kratos" schema in this database yet.
      # - DSN=postgres://muser:mpassword@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4&search_path=kratos
      - DSN=postgres://chatuser:chatpassword@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    networks:
      - intranet

  kratos:
    image: oryd/kratos:v1.2.0
    env_file:
      - .env
    ports:
      - 4433:4433
      - 4434:4434
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    networks:
      - intranet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # TODO: Change it to mailhog
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
    networks:
      - intranet
