origins:
  - "http://localhost:4200"

frontend_url: "http://localhost:4200"
port: 8082
kratos_url: "http://localhost:4433"
static_assets: "<absolute path to assets folder>/assets"

hooks:
  port: 8060

