- id: "api:profile"
  upstream:
    preserve_host: true
    url: "http://kratos_proxy:8000"
    strip_path: /api/v2/auth
  match:
    url: "http://localhost:8080/api/v2/auth<**>"
    methods:
      - GET
      - PATCH
      - POST
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow

- id: "api:profile"
  upstream:
    preserve_host: true
    url: "http://profile:8082"
    strip_path: /api/v2/profile
  match:
    url: "http://localhost:8080/api/v2/auth<**>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: json
