- id: "api:profile"
  upstream:
    preserve_host: true
    url: "http://service_profile:8000"
    strip_path: /api/v2/auth
  match:
    url: "http://localhost:8080/api/v2/auth<**>"
    methods:
      - GET
      - PATCH
      - POST
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow

- id: "api:chat"
  upstream:
    preserve_host: true
    url: "http://service_chat:8083"
  match:
    url: "http://localhost:8080/ws"
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: json
# https://www.ory.sh/docs/oathkeeper/guides/proxy-websockets