- id: "api:profile"
  upstream:
    preserve_host: true
    url: "http://service_profile:8082"
    strip_path: /api/v2/profile
  match:
    url: "http://127.0.0.1:8080/api/v2/profile<**>"
    methods:
      - GET
      - PATCH
      - POST
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: json

- id: "api:chat"
  upstream:
    preserve_host: true
    url: "ws://service_chat:8083"
  match:
    url: "ws://127.0.0.1:8080<**>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: json