name: ChatApp Workflow

on: [push]

jobs:
  release:
    name: release
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: 
      - style
      - tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release